### ISSUE TITLE
Cannot build 

### ISSUE THREAD

**Issue by ExileR** [NMan1/Modern-Warfare-Warzone-Cheat#1]
what is the problem, thanks in advance)
https://sun9-11.userapi.com/c858236/v858236331/1b05f0/Xtkwu41vr68.jpg

**Comment by NMan1** [comment]
This is basic programming, add extern to the functions with the error.

**Comment by ExileR** [comment]
But to which functions should I assign extern? Please help me figure it out)

**Comment by NMan1** [comment]
Did you even read the damn error? It tells you the exact issue... If you even bothered to put 1 minute into looking it up you’d have fixed it by now. I’m not the C++ Tech support. I already told you the solution.

**Comment by bytixo** [comment]
wich libraries do we need to link because it looks like to be a linker problem

**Comment by NMan1** [comment]
Make sure your building x64 Release

**Comment by bytixo** [comment]
https://streamable.com/7suhs don't want to bother you but here it is

**Comment by NMan1** [comment]
Add extern to the functions in the error

**Comment by bytixo** [comment]
thanks, I was doing from the start, now it works ty !!
![image](https://user-images.githubusercontent.com/60432755/77777031-36108100-704f-11ea-9501-756614a5d1d9.png)

**Comment by bytixo** [comment]
i think now you can close the issue @ExileR
