### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by Berns98** [NMan1/Modern-Warfare-Warzone-Cheat#11]
I'm getting these errors when compiling, any ideas?

Erro	LNK2001	símbolos externos indefinidos "void __cdecl d3d12hook::release(void)" (?release@d3d12hook@@YAXXZ)	Universal-ImGui-Hook	C:\Users\mateu\Downloads\Modern-Warfare-Warzone-Cheat-master\dllmain.obj	1	
Erro	LNK2001	símbolos externos indefinidos "void __cdecl d3d12hook::hookkDrawInstancedD3D12(struct ID3D12GraphicsCommandList *,unsigned int,unsigned int,unsigned int,unsigned int)" (?hookkDrawInstancedD3D12@d3d12hook@@YAXPEAUID3D12GraphicsCommandList@@IIII@Z)	Universal-ImGui-Hook	C:\Users\mateu\Downloads\Modern-Warfare-Warzone-Cheat-master\Global.obj	1	
Erro	LNK2001	símbolos externos indefinidos "void __cdecl d3d12hook::hookExecuteCommandListsD3D12(struct ID3D12CommandQueue *,unsigned int,struct ID3D12CommandList *)" (?hookExecuteCommandListsD3D12@d3d12hook@@YAXPEAUID3D12CommandQueue@@IPEAUID3D12CommandList@@@Z)	Universal-ImGui-Hook	C:\Users\mateu\Downloads\Modern-Warfare-Warzone-Cheat-master\Global.obj	1	
Erro	LNK2001	símbolos externos indefinidos "void __cdecl d3d12hook::hookDrawIndexedInstancedD3D12(struct ID3D12GraphicsCommandList *,unsigned int,unsigned int,unsigned int,int)" (?hookDrawIndexedInstancedD3D12@d3d12hook@@YAXPEAUID3D12GraphicsCommandList@@IIIH@Z)	Universal-ImGui-Hook	C:\Users\mateu\Downloads\Modern-Warfare-Warzone-Cheat-master\Global.obj	1	
Erro	LNK2001	símbolos externos indefinidos "void (__cdecl* d3d12hook::oExecuteCommandListsD3D12)(struct ID3D12CommandQueue *,unsigned int,struct ID3D12CommandList *)" (?oExecuteCommandListsD3D12@d3d12hook@@3P6AXPEAUID3D12CommandQueue@@IPEAUID3D12CommandList@@@ZEA)	Universal-ImGui-Hook	C:\Users\mateu\Downloads\Modern-Warfare-Warzone-Cheat-master\Global.obj	1	
Erro	LNK2001	símbolos externos indefinidos "void (__cdecl* d3d12hook::oDrawInstancedD3D12)(struct ID3D12GraphicsCommandList *,unsigned int,unsigned int,unsigned int,unsigned int)" (?oDrawInstancedD3D12@d3d12hook@@3P6AXPEAUID3D12GraphicsCommandList@@IIII@ZEA)	Universal-ImGui-Hook	C:\Users\mateu\Downloads\Modern-Warfare-Warzone-Cheat-master\Global.obj	1	
Erro	LNK2001	símbolos externos indefinidos "void (__cdecl* d3d12hook::oDrawIndexedInstancedD3D12)(struct ID3D12GraphicsCommandList *,unsigned int,unsigned int,unsigned int,int)" (?oDrawIndexedInstancedD3D12@d3d12hook@@3P6AXPEAUID3D12GraphicsCommandList@@IIIH@ZEA)	Universal-ImGui-Hook	C:\Users\mateu\Downloads\Modern-Warfare-Warzone-Cheat-master\Global.obj	1	
Erro	LNK2001	símbolos externos indefinidos "long __cdecl d3d12hook::hookSignalD3D12(struct ID3D12CommandQueue *,struct ID3D12Fence *,unsigned __int64)" (?hookSignalD3D12@d3d12hook@@YAJPEAUID3D12CommandQueue@@PEAUID3D12Fence@@_K@Z)	Universal-ImGui-Hook	C:\Users\mateu\Downloads\Modern-Warfare-Warzone-Cheat-master\Global.obj	1	
Erro	LNK2001	símbolos externos indefinidos "long __cdecl d3d12hook::hookPresentD3D12(struct IDXGISwapChain3 *,unsigned int,unsigned int)" (?hookPresentD3D12@d3d12hook@@YAJPEAUIDXGISwapChain3@@II@Z)	Universal-ImGui-Hook	C:\Users\mateu\Downloads\Modern-Warfare-Warzone-Cheat-master\Global.obj	1	
Erro	LNK2001	símbolos externos indefinidos "long (__cdecl* d3d12hook::oSignalD3D12)(struct ID3D12CommandQueue *,struct ID3D12Fence *,unsigned __int64)" (?oSignalD3D12@d3d12hook@@3P6AJPEAUID3D12CommandQueue@@PEAUID3D12Fence@@_K@ZEA)	Universal-ImGui-Hook	C:\Users\mateu\Downloads\Modern-Warfare-Warzone-Cheat-master\Global.obj	1	
Erro	LNK2001	símbolos externos indefinidos "long (__cdecl* d3d12hook::oPresentD3D12)(struct IDXGISwapChain *,unsigned int,unsigned int)" (?oPresentD3D12@d3d12hook@@3P6AJPEAUIDXGISwapChain@@II@ZEA)	Universal-ImGui-Hook	C:\Users\mateu\Downloads\Modern-Warfare-Warzone-Cheat-master\Global.obj	1	

PS: I tried installing the Directx SDK but that did'nt work
PS2: símbolos externos indefinidos = Undefined external symbols

**Comment by erDonko** [comment]
read the other threads

**Comment by NMan1** [comment]
I I've answered this in every other issue 20 times.
