### ISSUE TITLE
LNK2001: Unable to compile

### ISSUE THREAD

**Issue by rwds-root** [NMan1/Modern-Warfare-Warzone-Cheat#7]
`1>dllmain.obj : error LNK2001: unresolved external symbol "void __cdecl d3d12hook::release(void)" (?release@d3d12hook@@YAXXZ)
1>Global.obj : error LNK2001: unresolved external symbol "long __cdecl d3d12hook::hookPresentD3D12(struct IDXGISwapChain3 *,unsigned int,unsigned int)" (?hookPresentD3D12@d3d12hook@@YAJPEAUIDXGISwapChain3@@II@Z)
1>Global.obj : error LNK2001: unresolved external symbol "void __cdecl d3d12hook::hookkDrawInstancedD3D12(struct ID3D12GraphicsCommandList *,unsigned int,unsigned int,unsigned int,unsigned int)" (?hookkDrawInstancedD3D12@d3d12hook@@YAXPEAUID3D12GraphicsCommandList@@IIII@Z)
1>Global.obj : error LNK2001: unresolved external symbol "void __cdecl d3d12hook::hookDrawIndexedInstancedD3D12(struct ID3D12GraphicsCommandList *,unsigned int,unsigned int,unsigned int,int)" (?hookDrawIndexedInstancedD3D12@d3d12hook@@YAXPEAUID3D12GraphicsCommandList@@IIIH@Z)
1>Global.obj : error LNK2001: unresolved external symbol "void __cdecl d3d12hook::hookExecuteCommandListsD3D12(struct ID3D12CommandQueue *,unsigned int,struct ID3D12CommandList *)" (?hookExecuteCommandListsD3D12@d3d12hook@@YAXPEAUID3D12CommandQueue@@IPEAUID3D12CommandList@@@Z)
1>Global.obj : error LNK2001: unresolved external symbol "long __cdecl d3d12hook::hookSignalD3D12(struct ID3D12CommandQueue *,struct ID3D12Fence *,unsigned __int64)" (?hookSignalD3D12@d3d12hook@@YAJPEAUID3D12CommandQueue@@PEAUID3D12Fence@@_K@Z)
1>Global.obj : error LNK2001: unresolved external symbol "long (__cdecl* d3d12hook::oPresentD3D12)(struct IDXGISwapChain *,unsigned int,unsigned int)" (?oPresentD3D12@d3d12hook@@3P6AJPEAUIDXGISwapChain@@II@ZEA)
1>Global.obj : error LNK2001: unresolved external symbol "void (__cdecl* d3d12hook::oDrawInstancedD3D12)(struct ID3D12GraphicsCommandList *,unsigned int,unsigned int,unsigned int,unsigned int)" (?oDrawInstancedD3D12@d3d12hook@@3P6AXPEAUID3D12GraphicsCommandList@@IIII@ZEA)
1>Global.obj : error LNK2001: unresolved external symbol "void (__cdecl* d3d12hook::oDrawIndexedInstancedD3D12)(struct ID3D12GraphicsCommandList *,unsigned int,unsigned int,unsigned int,int)" (?oDrawIndexedInstancedD3D12@d3d12hook@@3P6AXPEAUID3D12GraphicsCommandList@@IIIH@ZEA)
1>Global.obj : error LNK2001: unresolved external symbol "void (__cdecl* d3d12hook::oExecuteCommandListsD3D12)(struct ID3D12CommandQueue *,unsigned int,struct ID3D12CommandList *)" (?oExecuteCommandListsD3D12@d3d12hook@@3P6AXPEAUID3D12CommandQueue@@IPEAUID3D12CommandList@@@ZEA)
1>Global.obj : error LNK2001: unresolved external symbol "long (__cdecl* d3d12hook::oSignalD3D12)(struct ID3D12CommandQueue *,struct ID3D12Fence *,unsigned __int64)" (?oSignalD3D12@d3d12hook@@3P6AJPEAUID3D12CommandQueue@@PEAUID3D12Fence@@_K@ZEA)
1>C:\Users\nginx\Downloads\Modern-Warfare-Warzone-Cheat-master\x64\Release\Universal-ImGui-Hook.dll : fatal error LNK1120: 11 unresolved externals`

I am unable to compile due to this issue. What am I doing wrong? I would really appreciate any help.

**Comment by NMan1** [comment]
A simple google search would answer your question... Remove extern from those functions.

**Comment by rwds-root** [comment]
> A simple google search would answer your question... Remove extern from those functions.

Sorry, but my noob ass still needs your help. I didn't exactly understand how do I remove extern from these functions. Can you please give me a tip?

**Comment by ExileR** [comment]
[Modern-Warfare-Warzone-Cheat-master.zip](https://github.com/NMan1/Modern-Warfare-Warzone-Cheat/files/4397850/Modern-Warfare-Warzone-Cheat-master.zip)
the old source on the idea of ​​no errors for u

**Comment by rwds-root** [comment]
> [Modern-Warfare-Warzone-Cheat-master.zip](https://github.com/NMan1/Modern-Warfare-Warzone-Cheat/files/4397850/Modern-Warfare-Warzone-Cheat-master.zip)
> the old source on the idea of ​​no errors for u

What do you mean?

**Comment by Barduki777** [comment]
include Hook.h in Hook.cpp.

**Comment by rwds-root** [comment]
> include Hook.h in Hook.cpp.
Thanks, I managed to compile by doing this. When I enable ESP, my game instantly crashes. Also Text & Snap options won't work.

**Comment by xKarmaSs** [comment]
my ass crashing to https://prnt.sc/rolvny

**Comment by rwds-root** [comment]
> my ass crashing to https://prnt.sc/rolvny

Yup, exactly the same error.

**Comment by NMan1** [comment]
The source is not updated fully. The pull request pushed only updated a few things. It’s up to you to fix the rest, all offsets and such can be found here https://www.unknowncheats.me/forum/other-fps-games/355326-call-duty-modern-warfare-21.html

**Comment by agent25147** [comment]
> > include Hook.h in Hook.cpp.
> 
> Thanks, I managed to compile by doing this. I am able to inject the dll just fine. But it crashes while loading the map.

can you help me compile too ? or better send me the compiled version

**Comment by windofxy** [comment]
> include Hook.h in Hook.cpp.
I've include it but i still can't compile
Why?

**Comment by DefaultO** [comment]
> > > include Hook.h in Hook.cpp.
> > 
> > 
> > Thanks, I managed to compile by doing this. I am able to inject the dll just fine. But it crashes while loading the map.
> 
> can you help me compile too ? or better send me the compiled version

You really don't want to have a compiled read-to-use version from someone who don't even can paste without instructions on how to get rid of those errors. He probably haven't changed hooking yet.

**Comment by windofxy** [comment]
> > > > include Hook.h in Hook.cpp.
> > > 
> > > 
> > > Thanks, I managed to compile by doing this. I am able to inject the dll just fine. But it crashes while loading the map.
> > 
> > 
> > can you help me compile too ? or better send me the compiled version
> 
> You really don't want to have a compiled ready-to-use version from someone who don't even can paste without instructions on how to get rid of those errors. He probably haven't changed hooking yet too which will get you certainly banned after injecting.

Hey,bro!Have you successfully compiled this hack?Pls tell me how to compile it.I tried as many method as i can.And I still can't compile it :(

**Comment by NMan1** [comment]
I don’t understand how some of you guys are having so many damn issues? Please turn off your computer and throw it out the window. If you can’t devote 3 minuets into looking at the other issues (which have had this issue and either I’ve commented with the solution or someone else did) then you shouldn’t have a computer more or less WiFi. Please get a brain for the sake of the people that do have a brain reading these comments.

**Comment by windofxy** [comment]
> I don’t understand how some of you guys are having so many damn issues? Please turn off your computer and throw it out the window. If you can’t devote 3 minuets into looking at the other issues (which have had this issue and either I’ve commented with the solution or someone else did) then you shouldn’t have a computer more or less WiFi. Please get a brain for the sake of the people that do have a brain reading these comments.

I've tried the method in the closed Issue.And I didn't get the work done

**Comment by windofxy** [comment]
Should I add extern to the functions with the error.Or remove extern??

**Comment by windofxy** [comment]
you said two different method to solve the problem

**Comment by windofxy** [comment]
One in this issue , and another one in a closed issue

**Comment by NMan1** [comment]
> > I don’t understand how some of you guys are having so many damn issues? Please turn off your computer and throw it out the window. If you can’t devote 3 minuets into looking at the other issues (which have had this issue and either I’ve commented with the solution or someone else did) then you shouldn’t have a computer more or less WiFi. Please get a brain for the sake of the people that do have a brain reading these comments.
> 
> I've tried the method in the closed Issue.And I didn't get the work done

Any issue you could have related to compiling has been answered here if your using the default source. It’s simply not possible to have so many damn issues like your having if you used the source I put out. It probably took you hours to even get visual studio installed properly. People like you really make me not want to post sources like this from the brain cells I lose reading this shit. 

I’m happy to help anyone, no matter how simple the question/fault may be. As long as they show they’re trying.

**Comment by NMan1** [comment]
> Should I add extern to the functions with the error.Or remove extern??

Have you even tried looking the fucking ERROR UP IN GOOGLE????? Any issue you could possibly have can be fixed with 10 minuets of searching in google!!!

**Comment by windofxy** [comment]
I searched it in Google

**Comment by NMan1** [comment]
> I searched it in Google

Well then there’s obviously no help for you in programming. Please stop spamming this thread.

**Comment by windofxy** [comment]
That why i return to here and ask the question

**Comment by agent25147** [comment]
> > Should I add extern to the functions with the error.Or remove extern??
> 
> Have you even tried looking the fucking ERROR UP IN GOOGLE????? Any issue you could possibly have can be fixed with 10 minuets of searching in google!!! This is the most simplest shit!!!! How will you even update the offsets if you can’t fix a extern linker error?

sir fixed basic library errors , i dont code in c++ thats why i was asking for help we really appreciate you posted the source but here's a simple request to post the compiled one too , the one working for you

**Comment by NMan1** [comment]
Your not building it with the right settings. You should only get 1 compilation error (a linker error) which I’ve said and many other hows to fix. Any other errors can be fixed with google. Anyone that respond to this issue I’m just going to block, complete waste of my time now.

**Comment by playfuldreamz** [comment]
> like your having if you used the source I put out. It probably took you hours

yeah this guys is a piece of shit innit
